USE [master]
GO
/****** Object:  Database [Sample_DB]    Script Date: 24-08-2023 11:22:01 ******/
CREATE DATABASE [Sample_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sample_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Sample_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sample_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Sample_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Sample_DB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sample_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sample_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sample_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sample_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sample_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sample_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sample_DB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Sample_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sample_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sample_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sample_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sample_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sample_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sample_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sample_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sample_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Sample_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sample_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sample_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sample_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sample_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sample_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sample_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sample_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Sample_DB] SET  MULTI_USER 
GO
ALTER DATABASE [Sample_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sample_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sample_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sample_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sample_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Sample_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Sample_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [Sample_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Sample_DB]
GO
/****** Object:  UserDefinedFunction [dbo].[GetProduct]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION  [dbo].[GetProduct]( @id int )
RETURNS nvarchar(50)
AS
BEGIN
	declare @result nvarchar(50)
    select @result =  Product.product_name from Product  Where Product.product_id = @id
	return @result
END
GO
/****** Object:  Table [dbo].[Product]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[product_id] [int] IDENTITY(1,1) NOT NULL,
	[product_name] [nvarchar](50) NOT NULL,
	[supplier_id] [int] NOT NULL,
	[unit_price] [int] NOT NULL,
	[package] [nvarchar](50) NULL,
	[is_discontinued] [nvarchar](50) NULL,
 CONSTRAINT [PK_Product_id] PRIMARY KEY CLUSTERED 
(
	[product_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[GetProductTabled]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION  [dbo].[GetProductTabled]( @id int )
RETURNS TABLE
AS
return select product_name, Product.unit_price from Product  Where Product.product_id = @id

--select * from Product
--select [dbo].[GetProduct](2) as 'Product Name'
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[customer_id] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [nvarchar](50) NOT NULL,
	[last_name] [nvarchar](50) NOT NULL,
	[city] [nvarchar](50) NOT NULL,
	[country] [nvarchar](50) NOT NULL,
	[phone] [int] NOT NULL,
 CONSTRAINT [PK_Customer_customer_id] PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order_item]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order_item](
	[orderitem_id] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NOT NULL,
	[product_id] [int] NOT NULL,
	[unit_price] [int] NOT NULL,
	[quantity] [int] NOT NULL,
 CONSTRAINT [PK_Orderitm_orderitem_id] PRIMARY KEY CLUSTERED 
(
	[orderitem_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordertbl]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordertbl](
	[order_id] [int] IDENTITY(1,1) NOT NULL,
	[order_date] [date] NOT NULL,
	[customer_id] [int] NOT NULL,
	[total_amount] [float] NOT NULL,
 CONSTRAINT [PK_Order_order_id] PRIMARY KEY CLUSTERED 
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Supplier]    Script Date: 24-08-2023 11:22:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Supplier](
	[supplier_id] [int] IDENTITY(1,1) NOT NULL,
	[company_name] [nvarchar](50) NOT NULL,
	[contact_name] [nvarchar](50) NOT NULL,
	[city] [nvarchar](50) NOT NULL,
	[country] [nvarchar](50) NOT NULL,
	[phone] [int] NOT NULL,
	[fax] [nvarchar](50) NULL,
 CONSTRAINT [PK_Supplier_id] PRIMARY KEY CLUSTERED 
(
	[supplier_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Order_item]  WITH CHECK ADD  CONSTRAINT [FK_Orderitm_Order_id] FOREIGN KEY([order_id])
REFERENCES [dbo].[Ordertbl] ([order_id])
GO
ALTER TABLE [dbo].[Order_item] CHECK CONSTRAINT [FK_Orderitm_Order_id]
GO
ALTER TABLE [dbo].[Order_item]  WITH CHECK ADD  CONSTRAINT [FK_Product_product_id] FOREIGN KEY([product_id])
REFERENCES [dbo].[Product] ([product_id])
GO
ALTER TABLE [dbo].[Order_item] CHECK CONSTRAINT [FK_Product_product_id]
GO
ALTER TABLE [dbo].[Ordertbl]  WITH CHECK ADD  CONSTRAINT [FK_Order_customer_id] FOREIGN KEY([customer_id])
REFERENCES [dbo].[Customer] ([customer_id])
GO
ALTER TABLE [dbo].[Ordertbl] CHECK CONSTRAINT [FK_Order_customer_id]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Supplier_id] FOREIGN KEY([supplier_id])
REFERENCES [dbo].[Supplier] ([supplier_id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Supplier_id]
GO
USE [master]
GO
ALTER DATABASE [Sample_DB] SET  READ_WRITE 
GO
